fix compatibility with django_cms 3.1
PlaceholderAdmin was deprecated some time ago In 3.1 it was removed.
This fixes following Exception:
    from cms.admin.placeholderadmin import PlaceholderAdmin
ImportError: cannot import name PlaceholderAdmin